################################################################################
# GNU makefile
# File Name: makefile
################################################################################


# Default target
writer: writer.c
	gcc writer.c -o writer

clean:
	rm -f *.o *.out writer
